esphome:
  name: kingsong-euc
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

external_components:
  source: github://lufton/esphome-kingsong-euc@main

ble_client:
  id: euc_client
  mac_address: !secret euc_mac

kingsong_euc:
  ble_client_id: euc_client

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

logger:
  level: WARN

binary_sensor:
  - platform: kingsong_euc
    charging:
      name: Charging
    fan:
      name: Fan
    gyroscope_error:
      name: Gyroscope error
    hall_sensor_error:
      name: Hall sensor error
    phase_short_circuit:
      name: Phase short circuit

button:
  - platform: kingsong_euc
    beep:
      name: Beep
    horn:
      name: Horn
    power_off:
      name: Power off

lock:
  - platform: kingsong_euc
    lock:
      name: Lock

number:
  - platform: kingsong_euc
    alarm_1:
      name: Alarm 1
    alarm_2:
      name: Alarm 2
    alarm_3:
      name: Alarm 3
    command:
      name: Command
    standby_delay:
      name: Standby delay
    tilt_back:
      name: Tilt back

select:
  - platform: kingsong_euc
    magic_light_mode:
      name: Magic light mode
    main_light_mode:
      id: main_light_mode
      name: Main light mode
    ride_mode:
      name: Ride mode
    spectrum_light_mode:
      name: Spectrum light mode
    voice_language:
      name: Voice language

sensor:
  - platform: kingsong_euc
    bms_count: 2
    cell_count: 30
    bms_cell_voltage:
      name: BMS cell voltage
    bms_current:
      name: BMS current
      hysteresis: 0.1
    bms_factory_capacity:
      name: BMS factory capacity
    bms_full_cycles:
      name: BMS full cycles
    bms_mosfet_temperature:
      name: BMS mosfet temperature
    bms_remaining_capacity:
      name: BMS remaining capacity
    bms_soc:
      name: BMS SoC
    bms_temperature_1:
      name: BMS temperature 1
    bms_temperature_2:
      name: BMS temperature 2
    bms_temperature_3:
      name: BMS temperature 3
    bms_temperature_4:
      name: BMS temperature 4
    bms_temperature_5:
      name: BMS temperature 5
    bms_temperature_6:
      name: BMS temperature 6
    bms_voltage:
      name: BMS voltage
      hysteresis: 0.1
    current:
      name: Current
      hysteresis: 0.1
    cpu_load:
      name: CPU load
    error_code:
      name: Error code
    mosfet_temperature:
      name: Mosfet temperature
    motor_temperature:
      name: Motor temperature
    odometer:
      name: Odometer
      hysteresis: 0.01
    power:
      name: Power
      hysteresis: 5
    pwm:
      name: PWM
    ride_time:
      name: Ride time
      hysteresis: 10
    speed:
      name: Speed
      hysteresis: 0.5
    speed_limit:
      name: Speed limit
    trip_distance:
      name: Trip distance
      hysteresis: 0.01
    trip_max_speed:
      name: Trip max speed
    uptime:
      name: Uptime
      hysteresis: 10
    voltage:
      name: Voltage
      hysteresis: 0.1

switch:
  - platform: kingsong_euc
    circle_light:
      name: Circle light
    lift_sensor:
      name: Lift sensor
    music_bluetooth:
      name: Music bluetooth
    spectrum_light:
      name: Spectrum light
    strobe:
      name: Strobe
    voice:
      name: Voice

text_sensor:
  - platform: kingsong_euc
    bms_count: 2
    bms_firmware:
      name: BMS firmware
    bms_manufacture_date:
      name: BMS manufacture date
    bms_serial:
      name: BMS serial
    charging_status:
      name: Charging status
    error_description:
      name: Error description
    model:
      name: Model
    serial:
      name: Serial
